---
apiVersion: v1
kind: ConfigMap
metadata:
  name: goals-configuration
  labels:
    app: fiufit
    tier: goals-microservice
data:
  GOALS_DB_HOST: "dpg-cikrbnlph6eg6ke1cgbg-a.oregon-postgres.render.com"
  GOALS_DB_DATABASE: fiufit_4evp
  GOALS_DB_USER: "fiufit"
  GOALS_DB_PASSWORD: $USERS_DB_PASSWORD
  GOALS_LOG_LEVEL: INFO
  GOALS_AUTH_HOST: auth-service.taller2-marianocinalli.svc.cluster.local:8002
  GOALS_TEST_IS_TESTING: "False"
  GOALS_SENTRY_ENABLED: "true"
  GOALS_SENTRY_DSN: $GOALS_SENTRY_DSN
  NEW_RELIC_LICENSE_KEY: $USERS_NEW_RELIC_KEY
  NEW_RELIC_APP_NAME: goals
  NEW_RELIC_MONITOR_MODE: "true"
  NEW_RELIC_LOG: stderr
  NEW_RELIC_LOG_LEVEL: warning
