---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goals
  labels:
    app: fiufit
    tier: goals-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiufit
      tier: goals-microservice
  template:
    metadata:
      labels:
        app: fiufit
        tier: goals-microservice
    spec:
      containers:
      - name: goals
        image: marianocinalli/goals:v0.0.4
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: goals-configuration
        ports:
          - containerPort: 8004
            name: http-goals
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 128Mi
            cpu: "0.2"
