---
apiVersion: v1
kind: Service
metadata:
  name: goals-service
  labels:
    app: fiufit
    tier: goals-service
spec:
  type: ClusterIP
  ports:
  - name: goals-svc
    protocol: TCP
    port: 8004
    targetPort: http-goals
  selector:
    app: fiufit
    tier: goals-microservice
